Merge request dio_pza => main
Panduza/panduza-py-legacy pull request #55
Opened 2023-05-10 09:05 UTC by MageTomcat14

Merge request to main, of driver to control IO using MODBUS

2023-05-10 09:20 UTC, XdoctorwhoZ requested changes
I feel like you didn't rebase you branch on top of the main work since a while... Can you try to rebase before ? or fix my comments

2023-05-10 09:20 UTC, XdoctorwhoZ commented on platform/panduza_platform/connectors/modbus_client_serial.py
> +from loguru import logger
loguru is not in the panduza-py anymore, it must be removed

2023-05-10 09:20 UTC, XdoctorwhoZ commented on platform/panduza_platform/connectors/udev_tty.py
> -        if serial_short and (serial_short != properties["ID_SERIAL_SHORT"]):
ID_SERIAL_SHORT doit être conservé

2023-05-10 09:20 UTC, XdoctorwhoZ commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +                "name": "paul_control_io",
This is an exemple for users, your name must not be displayed here

2023-05-10 09:20 UTC, XdoctorwhoZ commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +                "compatible": ["pza_modbus_dio","driver_of_PaulFisher", "py.pza_modbus_dio"], # name to put in the tree.json
Name problem again

2023-05-10 09:20 UTC, XdoctorwhoZ commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +        gpio_id = self.settings["gpio_id"]
you get the gpio_id but you don't use it...

2023-05-10 09:20 UTC, XdoctorwhoZ commented on platform/requirements.txt
> +loguru==0.6.0
must not be there anymore

2023-05-10 10:07 UTC, MageTomcatF14 commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +                "compatible": ["pza_modbus_dio","driver_of_PaulFisher", "py.pza_modbus_dio"], # name to put in the tree.json
corrigé

2023-05-10 10:07 UTC, MageTomcat14 commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +                "name": "paul_control_io",
corrigé

2023-05-10 10:09 UTC, MageTomcat14 commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +        gpio_id = self.settings["gpio_id"]
Oui, en effet. Je l'utilise pas ici.

2023-05-10 11:45 UTC, MageTomcatF14 commented on platform/panduza_platform/connectors/udev_tty.py
> -        if serial_short and (serial_short != properties["ID_SERIAL_SHORT"]):
Le ID_SERIAL_SHORT est maintenant passé en paramètre lors de l'init du connecteur.

2023-05-10 13:54 UTC, MageTomcatF14 commented
Le loguru est enlevé

2023-05-10 14:00 UTC, MageTomcatF14 commented on platform/panduza_platform/connectors/modbus_client_serial.py
> +from loguru import logger
c'est fait

2023-05-10 14:01 UTC, MageTomcatF14 commented on platform/requirements.txt
> +loguru==0.6.0
c'est fait

2023-05-15 05:37 UTC, XdoctorwhoZ requested changes
On avance c'est bien, maintenant que tu sais faire un code qui fonctionne, je demande un code bien finalisé et propre.

2023-05-15 05:37 UTC, XdoctorwhoZ commented on platform/panduza_platform/connectors/udev_tty.py
> +from loguru import logger
loguru still there

2023-05-15 05:37 UTC, XdoctorwhoZ commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +            self.modbus._ConnectorModbusClientSerial__instances["active_low"] = self.__dir["state"]["active_low"]
Cette section doit être optimisée, trop de code redondant... ça gâche la visibilité

2023-05-15 05:37 UTC, XdoctorwhoZ commented on platform/requirements.txt
> +loguru==0.6.0
Il faut enlever la ligne

2023-05-15 05:37 UTC, XdoctorwhoZ commented on tests/requirements.txt
> +loguru
Il faut enlever la ligne

2023-05-15 05:37 UTC, XdoctorwhoZ commented on platform/panduza_platform/my_robot.robot
> +*** Settings ***
C'est quoi ce fichier ??? pourquoi il est la ?

2023-05-15 05:37 UTC, XdoctorwhoZ commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +        valueio_0 = self.modbus._ConnectorModbusClientSerial__instances.get("value_i0")
Je ne comprends pas ce block de code.

2023-05-15 05:37 UTC, XdoctorwhoZ commented on platform/panduza_platform/connectors/modbus_client_serial.py
> +
Attention à la propreté de tes modifications ! (active les caractères invisible sur VSCode)

2023-05-15 07:23 UTC, MageTomcat14 commented on platform/panduza_platform/my_robot.robot
> +*** Settings ***
le fichier est supprimé

2023-05-15 07:24 UTC, MageTomcat14 commented on tests/requirements.txt
> +loguru
j'avais oublié de commiter les fichiers ou j'ai enlevé les loguru

2023-05-15 07:24 UTC, MageTomcatF14 commented on platform/requirements.txt
> +loguru==0.6.0
j'avais oublié de commiter les fichiers ou j'ai enlevé les loguru

2023-05-15 07:24 UTC, MageTomcat14 commented on platform/panduza_platform/connectors/udev_tty.py
> +from loguru import logger
j'avais oublié de commiter les fichiers ou j'ai enlevé les loguru

2023-05-15 09:06 UTC, MageTomcatF14 commented on platform/panduza_platform/drivers/dio/pza_modbus_dio.py
> +        valueio_0 = self.modbus._ConnectorModbusClientSerial__instances.get("value_i0")
Ce bloc de code permet de récupérer la clé "value_io" du dictionnaire d'instance initialisé dans le connecteur. Toutefois, j'ai revu la méthode pour cette partie.

2023-05-24 05:57 UTC, XdoctorwhoZ approved these changes

2023-05-24 05:58 UTC, merged

2023-05-24 05:59 UTC, XdoctorwhoZ commented
@MageTomcat14 tips for the next time, break big merge requests into smallers ones.

2023-05-24 07:03 UTC, MageTomcat14 commented
Okay, I will take that into account